name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup and Build
        uses: ./.github/actions/setup-and-build

      - name: Run type check
        run: pnpm run typecheck

      - name: Run tests
        run: pnpm run test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change this to your AWS region

      - name: Deploy to S3
        if: always()
        run: |
          # Example for deploying to S3
          aws s3 sync ./build s3://your-s3-bucket-name --delete

      - name: Deploy to EC2 (optional)
        if: always()
        run: |
          # Example for deploying to EC2
          ssh -i ${{ secrets.EC2_KEY_PAIR_PATH }} ec2-user@<EC2_PUBLIC_IP> <<EOF
          cd /path/to/app
          git pull origin master
          pnpm install --production
          pm2 restart all
          EOF
